### ISSUE TITLE
Login Issues for first time

### ISSUE THREAD

**Issue by jgkamat** [jasminb/megastoragemanager#54]
Hi! I just tried installing your app, but when I login, I get this 'unexpected response' error message. The official mega client seems to log in fine at the same time. Do you have any idea what it could be?

![screenshot_20160719-183339](https://cloud.githubusercontent.com/assets/4349709/16972434/452b6bf4-4de0-11e6-87dc-8b52b29e24f1.png)

**Comment by jasminb** [comment]
Hey, it could be DNS related. Can you try to use 8.8.8.8 as your DNS?

**Comment by jgkamat** [comment]
Nope, that didn't help :cry: 

The error seems to occur on the 'fetching remote folders' step.

**Comment by jasminb** [comment]
Can you try creating new account, finish two step registration and try logging in.

Another thing that would be very helpful would be if you could provide application logs (http://stackoverflow.com/questions/2882253/how-do-i-get-the-logfile-from-an-android-device)

**Comment by jgkamat** [comment]
It does indeed work on a new account! I have a ton of folders in my main mega account, maybe the operation to get folders is timing out? Logging in w/ the official app takes quite a bit of time. 

I'll try to get some log data when I get home tonight.

**Comment by jgkamat** [comment]
After clearing the trash on my mega account (which had a ton of folders in syncdebris) I was able to login! It would be nice to fix this issue so I don't see it again though =)

**Comment by jasminb** [comment]
Hey, if you can provide some logs, I would be more than happy to look at it and fix it.

**Comment by jgkamat** [comment]
I can't repoduce this any more (since I deleted the trash without backing it up...).

I'll reopen this if I run into it again. Thanks for the suggestions!
